server:
  port: 30002
spring:
  application: #项目名
      name: service-helper
  datasource:
    # url: jdbc:mysql://rm-k2j9v1h9vm4025w07.mysql.zhangbei.rds.aliyuncs.com:3306/jingcaidailian?relaxAutoCommit=true&zeroDateTimeBehavior=convertToNull&autoReconnect=true&failOverReadOnly=false&useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    # url: jdbc:mysql://rm-k2j9v1h9vm4025w07.mysql.zhangbei.rds.aliyuncs.com:3306/jingcaidailian?relaxAutoCommit=true&zeroDateTimeBehavior=convertToNull&autoReconnect=true&failOverReadOnly=false&useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
   # username: jusr8ew6ubus
  #  password: Jingcai520
   # url: jdbc:mysql://rm-k2j9v1h9vm4025w07.mysql.zhangbei.rds.aliyuncs.com:3306/customer_helper?relaxAutoCommit=true&zeroDateTimeBehavior=convertToNull&autoReconnect=true&failOverReadOnly=false&useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    # url: jdbc:mysql://localhost:3306/customer_helper?relaxAutoCommit=true&zeroDateTimeBehavior=convertToNull&autoReconnect=true&failOverReadOnly=false&useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/customer_helper?useSSL=false&characterEncoding=utf-8&useOldAliasMetadataBehavior=true&autoReconnect=true&serverTimezone=GMT%2B8
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: true



#  jackson: ##json转换器
#    date-format: yyyy-MM-dd hh:mm:ss
#    joda-date-time-format: yyyy-MM-dd hh:mm:ss
#    time-zone: GMT+8
####扫xml包
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.sun.entity

logging:
  pattern:
    console: "%d - %msg%n"
  path: /usr/local/JAVA/Tomcat/customer/
 # path: C:\Users\Administrator.DESKTOP-9ULE43T\Desktop\
  level:
    com.sun.controller: error